"""Step A3: verify every nflverse loader, coverage year and column the spec relies on.

Downloads real data (current season, 2025, each dataset's claimed first season, and the year
before it to confirm the coverage start). Writes reports/verify_sources.json. The human-readable
conclusions go into docs/assumptions.md.

Run: uv run python scripts/verify_sources.py [dataset ...]
"""

from __future__ import annotations

import json
import sys
import time

import polars as pl

from twm.config import ROOT, settings
from twm.sources import nflverse as nv

CURRENT = settings().current_season

# Columns the spec (or our planned features) rely on. Best-known names; the report says which
# actually exist. Missing ones must be renamed in the spec/assumptions, never invented.
EXPECTED: dict[str, list[str]] = {
    "pbp": [
        "game_id",
        "season",
        "week",
        "game_date",
        "posteam",
        "defteam",
        "home_team",
        "away_team",
        "play_type",
        "down",
        "ydstogo",
        "yardline_100",
        "game_seconds_remaining",
        "half_seconds_remaining",
        "game_half",
        "score_differential",
        "posteam_timeouts_remaining",
        "defteam_timeouts_remaining",
        "posteam_score",
        "defteam_score",
        "epa",
        "wp",
        "vegas_wp",
        "home_wp",
        "wpa",
        "xpass",
        "cpoe",
        "xyac_epa",
        "xyac_mean_yardage",
        "air_yards",
        "yards_after_catch",
        "passer_player_id",
        "receiver_player_id",
        "rusher_player_id",
        "yards_gained",
        "touchdown",
        "pass_touchdown",
        "rush_touchdown",
        "complete_pass",
        "incomplete_pass",
        "interception",
        "fumble_lost",
        "two_point_attempt",
        "two_point_conv_result",
        "extra_point_result",
        "extra_point_attempt",
        "fourth_down_converted",
        "fourth_down_failed",
        "field_goal_result",
        "field_goal_attempt",
        "kick_distance",
        "punt_attempt",
        "timeout",
        "timeout_team",
        "penalty",
        "qb_kneel",
        "qb_spike",
        "spread_line",
        "total_line",
        "roof",
        "surface",
        "temp",
        "wind",
        "receive_2h_ko",
        "goal_to_go",
        "pass_location",
        "run_location",
        "shotgun",
        "no_huddle",
        "series_success",
        "drive",
        "qtr",
        "quarter_seconds_remaining",
        "sp",
        "fixed_drive_result",
        "aborted_play",
        "play_deleted",
        "success",
        "pass",
        "rush",
        "special",
        "desc",
        "home_coach",
        "away_coach",
        "div_game",
    ],
    "player_stats": [
        "player_id",
        "player_name",
        "player_display_name",
        "position",
        "position_group",
        "team",
        "recent_team",
        "opponent_team",
        "season",
        "week",
        "season_type",
        "completions",
        "attempts",
        "passing_yards",
        "passing_tds",
        "interceptions",
        "passing_interceptions",
        "sack_fumbles_lost",
        "passing_2pt_conversions",
        "carries",
        "rushing_yards",
        "rushing_tds",
        "rushing_fumbles_lost",
        "rushing_2pt_conversions",
        "receptions",
        "targets",
        "receiving_yards",
        "receiving_tds",
        "receiving_fumbles_lost",
        "receiving_air_yards",
        "receiving_yards_after_catch",
        "receiving_2pt_conversions",
        "target_share",
        "air_yards_share",
        "wopr",
        "racr",
        "fantasy_points",
        "fantasy_points_ppr",
    ],
    "schedules": [
        "game_id",
        "season",
        "game_type",
        "week",
        "gameday",
        "weekday",
        "gametime",
        "away_team",
        "home_team",
        "away_score",
        "home_score",
        "result",
        "total",
        "overtime",
        "location",
        "away_rest",
        "home_rest",
        "away_moneyline",
        "home_moneyline",
        "spread_line",
        "away_spread_odds",
        "home_spread_odds",
        "total_line",
        "under_odds",
        "over_odds",
        "div_game",
        "roof",
        "surface",
        "temp",
        "wind",
        "away_coach",
        "home_coach",
        "referee",
        "stadium_id",
        "stadium",
        "old_game_id",
        "espn",
        "pfr",
    ],
    "snap_counts": [
        "game_id",
        "pfr_game_id",
        "season",
        "game_type",
        "week",
        "player",
        "pfr_player_id",
        "position",
        "team",
        "opponent",
        "offense_snaps",
        "offense_pct",
        "defense_snaps",
        "defense_pct",
        "st_snaps",
        "st_pct",
    ],
    "injuries": [
        "season",
        "game_type",
        "team",
        "week",
        "gsis_id",
        "position",
        "full_name",
        "first_name",
        "last_name",
        "report_primary_injury",
        "report_secondary_injury",
        "report_status",
        "practice_primary_injury",
        "practice_status",
        "date_modified",
    ],
    "depth_charts": [
        "season",
        "week",
        "club_code",
        "team",
        "game_type",
        "depth_team",
        "last_name",
        "first_name",
        "football_name",
        "formation",
        "gsis_id",
        "jersey_number",
        "position",
        "elias_id",
        "depth_position",
        "full_name",
        "dt",
        "pos_grp",
        "pos_name",
        "pos_abb",
        "pos_slot",
        "pos_rank",
    ],
    "rosters": [
        "season",
        "team",
        "position",
        "depth_chart_position",
        "jersey_number",
        "status",
        "full_name",
        "first_name",
        "last_name",
        "birth_date",
        "height",
        "weight",
        "college",
        "gsis_id",
        "espn_id",
        "sportradar_id",
        "yahoo_id",
        "rotowire_id",
        "pff_id",
        "pfr_id",
        "fantasy_data_id",
        "sleeper_id",
        "years_exp",
        "headshot_url",
        "week",
        "game_type",
        "entry_year",
        "rookie_year",
        "draft_club",
        "draft_number",
    ],
    "rosters_weekly": [
        "season",
        "team",
        "position",
        "depth_chart_position",
        "status",
        "full_name",
        "birth_date",
        "gsis_id",
        "espn_id",
        "pfr_id",
        "sleeper_id",
        "years_exp",
        "week",
        "game_type",
        "entry_year",
        "rookie_year",
        "draft_club",
        "draft_number",
    ],
    "ngs_passing": [
        "season",
        "season_type",
        "week",
        "player_display_name",
        "player_position",
        "team_abbr",
        "player_gsis_id",
        "avg_time_to_throw",
        "avg_completed_air_yards",
        "avg_intended_air_yards",
        "aggressiveness",
        "completion_percentage_above_expectation",
        "attempts",
    ],
    "ngs_receiving": [
        "season",
        "season_type",
        "week",
        "player_gsis_id",
        "avg_cushion",
        "avg_separation",
        "avg_intended_air_yards",
        "percent_share_of_intended_air_yards",
        "receptions",
        "targets",
        "catch_percentage",
        "avg_yac",
        "avg_expected_yac",
        "avg_yac_above_expectation",
    ],
    "ngs_rushing": [
        "season",
        "season_type",
        "week",
        "player_gsis_id",
        "efficiency",
        "percent_attempts_gte_eight_defenders",
        "avg_time_to_los",
        "rush_attempts",
        "expected_rush_yards",
        "rush_yards_over_expected",
        "rush_yards_over_expected_per_att",
        "rush_pct_over_expected",
    ],
    "pfr_pass": [
        "season",
        "week",
        "game_id",
        "pfr_player_id",
        "team",
        "passing_drops",
        "times_pressured",
        "times_blitzed",
        "times_hurried",
    ],
    "pfr_rush": [
        "season",
        "week",
        "game_id",
        "pfr_player_id",
        "team",
        "carries",
        "rushing_broken_tackles",
        "rushing_yards_before_contact",
        "rushing_yards_after_contact",
    ],
    "pfr_rec": [
        "season",
        "week",
        "game_id",
        "pfr_player_id",
        "team",
        "receiving_drop",
        "receiving_broken_tackles",
        "receiving_int",
    ],
    "ftn_charting": [
        "nflverse_game_id",
        "nflverse_play_id",
        "season",
        "week",
        "is_play_action",
        "is_motion",
        "is_rpo",
        "n_blitzers",
        "n_pass_rushers",
        "is_screen_pass",
    ],
    "participation": [
        "nflverse_game_id",
        "play_id",
        "possession_team",
        "offense_formation",
        "offense_personnel",
        "defenders_in_box",
        "defense_personnel",
        "number_of_pass_rushers",
        "players_on_play",
        "offense_players",
        "defense_players",
        "n_offense",
        "n_defense",
        "ngs_air_yards",
        "time_to_throw",
        "was_pressure",
        "route",
        "defense_man_zone_type",
        "defense_coverage_type",
    ],
    "ff_opportunity": [
        "season",
        "week",
        "player_id",
        "full_name",
        "position",
        "team",
        "pass_attempt",
        "pass_completions_exp",
        "pass_yards_gained_exp",
        "pass_touchdown_exp",
        "receptions_exp",
        "rec_yards_gained_exp",
        "rec_touchdown_exp",
        "rush_yards_gained_exp",
        "rush_touchdown_exp",
        "pass_fantasy_points_exp",
        "rec_fantasy_points_exp",
        "rush_fantasy_points_exp",
        "total_fantasy_points_exp",
        "total_fantasy_points",
        "total_fantasy_points_diff",
        "rec_attempt",
        "rush_attempt",
        "receptions",
        "rec_yards_gained",
        "rec_touchdown",
        "rush_yards_gained",
        "rush_touchdown",
        "pass_completions",
        "pass_yards_gained",
        "pass_touchdown",
        "pass_interception",
        "pass_interception_exp",
        "pass_two_point_conv",
        "rec_two_point_conv",
        "rush_two_point_conv",
        "rec_fumble_lost",
        "rush_fumble_lost",
        "pass_first_down_exp",
        "game_id",
    ],
    "ff_opportunity_pass": [
        "season",
        "week",
        "game_id",
        "play_id",
        "receiver_player_id",
        "passer_player_id",
        "air_yards",
        "yardline_100",
        "down",
        "ydstogo",
        "pass_completion_exp",
        "yards_gained_exp",
        "pass_touchdown_exp",
        "rec_fantasy_points_exp",
        "pass_fantasy_points_exp",
    ],
    "ff_opportunity_rush": [
        "season",
        "week",
        "game_id",
        "play_id",
        "rusher_player_id",
        "yardline_100",
        "down",
        "ydstogo",
        "rush_yards_gained_exp",
        "rush_touchdown_exp",
        "rush_fantasy_points_exp",
    ],
    "draft_picks": [
        "season",
        "round",
        "pick",
        "team",
        "gsis_id",
        "pfr_player_id",
        "cfb_player_id",
        "pfr_player_name",
        "hof",
        "position",
        "category",
        "side",
        "college",
        "age",
        "to",
        "allpro",
        "probowls",
        "seasons_started",
    ],
    "combine": [
        "season",
        "draft_year",
        "draft_team",
        "draft_round",
        "draft_ovr",
        "pfr_id",
        "cfb_id",
        "player_name",
        "pos",
        "school",
        "ht",
        "wt",
        "forty",
        "bench",
        "vertical",
        "broad_jump",
        "cone",
        "shuttle",
    ],
    "ff_playerids": [
        "mfl_id",
        "sportradar_id",
        "fantasypros_id",
        "gsis_id",
        "pff_id",
        "sleeper_id",
        "nfl_id",
        "espn_id",
        "yahoo_id",
        "fleaflicker_id",
        "cbs_id",
        "pfr_id",
        "cfbref_id",
        "rotowire_id",
        "rotoworld_id",
        "ktc_id",
        "stats_id",
        "stats_global_id",
        "fantasy_data_id",
        "swish_id",
        "name",
        "merge_name",
        "position",
        "team",
        "birthdate",
        "age",
        "draft_year",
        "draft_round",
        "draft_pick",
        "draft_ovr",
        "twitter_username",
        "height",
        "weight",
        "college",
        "db_season",
    ],
    "ff_rankings_draft": [
        "fantasypros_id",
        "player_name",
        "pos",
        "team",
        "rank",
        "ecr",
        "sd",
        "best",
        "worst",
        "sportsdata_id",
        "yahoo_id",
        "cbs_id",
        "page_type",
        "scrape_date",
        "id",
    ],
    "ff_rankings_week": [
        "fantasypros_id",
        "player_name",
        "pos",
        "team",
        "rank",
        "ecr",
        "sd",
        "best",
        "worst",
        "page_type",
        "scrape_date",
        "id",
    ],
    "ff_rankings_all": [
        "fantasypros_id",
        "player_name",
        "pos",
        "team",
        "rank",
        "ecr",
        "sd",
        "best",
        "worst",
        "page_type",
        "scrape_date",
        "id",
        "ecr_type",
    ],
    "contracts": [
        "player",
        "position",
        "team",
        "is_active",
        "year_signed",
        "years",
        "value",
        "apy",
        "guaranteed",
        "apy_cap_pct",
        "inflated_value",
        "inflated_apy",
        "inflated_guaranteed",
        "player_page",
        "otc_id",
        "gsis_id",
        "date_of_birth",
        "height",
        "weight",
        "college",
        "draft_year",
        "draft_round",
        "draft_overall",
        "draft_team",
        "cols",
    ],
    "players": [
        "gsis_id",
        "display_name",
        "common_first_name",
        "first_name",
        "last_name",
        "short_name",
        "football_name",
        "esb_id",
        "nfl_id",
        "pfr_id",
        "pff_id",
        "otc_id",
        "espn_id",
        "smart_id",
        "birth_date",
        "position_group",
        "position",
        "height",
        "weight",
        "headshot",
        "college_name",
        "rookie_season",
        "last_season",
        "latest_team",
        "status",
        "draft_year",
        "draft_round",
        "draft_pick",
        "draft_team",
        "years_of_experience",
        "jersey_number",
    ],
    "teams": [
        "team_abbr",
        "team_name",
        "team_id",
        "team_nick",
        "team_conf",
        "team_division",
        "team_color",
        "team_color2",
        "team_color3",
        "team_color4",
        "team_logo_wikipedia",
        "team_logo_espn",
        "team_wordmark",
        "team_conference_logo",
        "team_league_logo",
        "team_logo_squared",
        "season",
    ],
    "team_stats": ["season", "week", "team", "opponent_team", "passing_epa", "rushing_epa"],
}

# Coverage years claimed in the spec Section 4.1 (verify: first year loads, year before fails).
CLAIMED_FIRST: dict[str, int] = {
    "pbp": 1999,
    "player_stats": 1999,
    "schedules": 1999,
    "snap_counts": 2012,
    "injuries": 2009,
    "depth_charts": 2001,
    "rosters": 1999,
    "rosters_weekly": 2002,
    "ngs_passing": 2016,
    "ngs_receiving": 2016,
    "ngs_rushing": 2016,
    "pfr_pass": 2018,
    "pfr_rush": 2018,
    "pfr_rec": 2018,
    "ftn_charting": 2022,
    "participation": 2016,
    "ff_opportunity": 2006,
    "ff_opportunity_pass": 2006,
    "ff_opportunity_rush": 2006,
    "draft_picks": 1980,
    "combine": 2000,
    "team_stats": 1999,
}


def try_fetch(name: str, season: int | None, **kw) -> tuple[pl.DataFrame | None, str | None]:
    t0 = time.time()
    try:
        df = nv.fetch(name, season, snapshot=False, **kw)
        return df, None
    except Exception as e:  # noqa: BLE001
        return None, f"{type(e).__name__}: {str(e)[:200]}"
    finally:
        print(f"  {name} {season}: {time.time() - t0:.1f}s", file=sys.stderr)


def probe(name: str) -> dict:
    ds = nv.DATASETS[name]
    out: dict = {
        "dataset": name,
        "loader": ds.loader,
        "kwargs": ds.kwargs,
        "per_season": ds.per_season,
    }
    frames: dict[str, pl.DataFrame] = {}
    if not ds.per_season:
        df, err = try_fetch(name, None, max_age_hours=0)  # always fresh for non-seasonal
        out["error"] = err
        if df is not None:
            frames["all"] = df
    else:
        first = CLAIMED_FIRST.get(name, ds.first_season or 1999)
        seasons = {
            "current": CURRENT,
            "prev": CURRENT - 1,
            "first": first,
            "before_first": first - 1,
        }
        # draft_picks/combine: "before_first" of 1980/2000 is meaningful too
        out["seasons"] = {}
        for label, season in seasons.items():
            df, err = try_fetch(name, season)
            rec = {"season": season, "error": err}
            if df is not None:
                rec.update(rows=df.height, cols=df.width)
                if "week" in df.columns and df.height:
                    wk = df["week"]
                    rec["week_min"] = wk.min()
                    rec["week_max"] = wk.max()
                if "season" in df.columns and df.height:
                    rec["season_values"] = sorted(df["season"].unique().to_list())[:5]
                frames[label] = df
            out["seasons"][label] = rec
    # Column check against the freshest frame that loaded, and note differences across eras.
    ref = next((frames[k] for k in ("current", "prev", "all", "first") if k in frames), None)
    if ref is not None:
        cols = set(ref.columns)
        exp = EXPECTED.get(name, [])
        out["expected_present"] = [c for c in exp if c in cols]
        out["expected_missing"] = [c for c in exp if c not in cols]
        out["actual_columns"] = {c: str(t) for c, t in ref.schema.items()}
        if "first" in frames and frames["first"] is not ref:
            fcols = set(frames["first"].columns)
            out["cols_only_in_first"] = sorted(fcols - cols)
            out["cols_only_in_current"] = sorted(cols - fcols)
        if "prev" in frames and "current" in frames:
            pc, cc = set(frames["prev"].columns), set(frames["current"].columns)
            out["cols_only_in_prev"] = sorted(pc - cc)
            out["cols_only_in_current_vs_prev"] = sorted(cc - pc)
    return out


def main(argv: list[str]) -> None:
    names = argv or list(nv.DATASETS)
    results = []
    for name in names:
        print(f"== {name}", file=sys.stderr)
        results.append(probe(name))
    out = ROOT / "reports" / "verify_sources.json"
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps(results, indent=1, default=str))
    print(f"wrote {out}")
    for r in results:
        miss = r.get("expected_missing", "?")
        err = r.get("error")
        print(f"{r['dataset']:22s} missing={miss} err={err}")


if __name__ == "__main__":
    main(sys.argv[1:])
